<?php namespace ProcessWire;

/**
 * Maid of Threads — ProcessWire Configuration
 *
 * Environment-aware: detects local vs production automatically.
 */

// ──────────────────────────────────────────────
// Environment Detection
// ──────────────────────────────────────────────
$isLocal = in_array($_SERVER['HTTP_HOST'] ?? '', [
    'localhost',
    'localhost:8080',
    '127.0.0.1',
    '127.0.0.1:8080',
]);

// ──────────────────────────────────────────────
// Database
// ──────────────────────────────────────────────
if ($isLocal) {
    $config->dbHost = 'db';           // Docker service name
    $config->dbName = 'mot_dev';
    $config->dbUser = 'mot_user';
    $config->dbPass = 'mot_password';
} else {
    // Production — update these with Krystal credentials
    $config->dbHost = 'localhost';
    $config->dbName = 'CHANGE_ME';
    $config->dbUser = 'CHANGE_ME';
    $config->dbPass = 'CHANGE_ME';
}

$config->dbPort = '3306';
$config->dbCharset = 'utf8mb4';
$config->dbEngine = 'InnoDB';

// ──────────────────────────────────────────────
// Hosts & URLs
// ──────────────────────────────────────────────
if ($isLocal) {
    $config->httpHosts = ['localhost:8080', 'localhost'];
    $config->https = false;
    $config->debug = true;
} else {
    // Production — update with your domain
    $config->httpHosts = [
        'demo.maidinthreads.tombritton.co.uk',
        'www.maidofthreads.co.uk', 'maidofthreads.co.uk',
        'www.maidofthreads.com', 'maidofthreads.com',
    ];
    $config->https = true;
    $config->debug = false;
}

// ──────────────────────────────────────────────
// General Settings
// ──────────────────────────────────────────────
$config->timezone = 'Europe/London';
$config->advanced = false;
$config->adminEmail = 'admin@maidofthreads.co.uk';

// ──────────────────────────────────────────────
// Security Salts (generated by installer — do not change)
// ──────────────────────────────────────────────
$config->userAuthSalt = '015e110c1df316ccf77031ee18cf9768dd60ece8f907059ca0d095b032b79b33';
$config->tableSalt = 'a2d5711c84aabc0dd60acc187e8144d3b57c104d';

// ──────────────────────────────────────────────
// Session
// ──────────────────────────────────────────────
$config->sessionName = 'pw197';
$config->sessionFingerprint = true;
if (!$isLocal) {
    $config->sessionCookieSecure = true;
}

// ──────────────────────────────────────────────
// Template Strategy: Delayed Output
// ──────────────────────────────────────────────
$config->prependTemplateFile = '_init.php';
$config->appendTemplateFile = '_main.php';

// ──────────────────────────────────────────────
// File & Image Settings
// ──────────────────────────────────────────────
$config->chmodDir = '0755';
$config->chmodFile = '0644';
$config->imageSizerOptions('webpAdd', true);  // Auto-generate WebP variants

// ──────────────────────────────────────────────
// Admin
// ──────────────────────────────────────────────
$config->defaultAdminTheme = 'AdminThemeUikit';
// Custom admin URL — obscures the default /processwire/ path from bots
$config->urls->admin = '/mot-studio/';

// ──────────────────────────────────────────────
// Stripe Payment Configuration
// ──────────────────────────────────────────────
// Keys are loaded from environment variables (set in docker/.env locally,
// or server environment in production). Never commit real keys to git.
$config->stripePublicKey    = getenv('STRIPE_PUBLIC_KEY') ?: 'pk_test_CHANGE_ME';
$config->stripeSecretKey    = getenv('STRIPE_SECRET_KEY') ?: 'sk_test_CHANGE_ME';
$config->stripeWebhookSecret = getenv('STRIPE_WEBHOOK_SECRET') ?: 'whsec_CHANGE_ME';

// ──────────────────────────────────────────────
// Shop Settings
// ──────────────────────────────────────────────
$config->shopCurrency = 'gbp';
$config->shopCurrencySymbol = '£';
$config->shopVatRate = 0.20;           // 20% UK VAT
$config->shopPricesIncludeVat = true;  // Display prices inclusive of VAT
$config->shopFlatShipping = 3.95;      // Flat shipping rate in GBP
$config->shopFreeShippingThreshold = 50.00; // Free shipping above this

// ──────────────────────────────────────────────
// Installer metadata (do not change)
// ──────────────────────────────────────────────
$config->installed = 1772659222;
